export const categories = [
	{
		id: "design",
		title: "Design",
		jobsAvailable: 235,
		icon: "/Icon.svg",
	},
	{
		id: "sales",
		title: "Sales",
		jobsAvailable: 756,
		icon: "/Icon-1.svg",
	},
	{
		id: "marketing",
		title: "Marketing",
		jobsAvailable: 140,
		icon: "/Icon-2.svg",
	},
	{
		id: "finance",
		title: "Finance",
		jobsAvailable: 325,
		icon: "/Icon-3.svg",
	},
	{
		id: "technology",
		title: "Technology",
		jobsAvailable: 436,
		icon: "/Icon-4.svg",
	},
	{
		id: "engineering",
		title: "Engineering",
		jobsAvailable: 436,
		icon: "/Icon-5.svg",
	},
	{
		id: "business",
		title: "Business",
		jobsAvailable: 436,
		icon: "/Icon-6.svg",
	},
	{
		id: "human-resources",
		title: "Human Resources",
		jobsAvailable: 436,
		icon: "/Icon-7.svg",
	},
];

export const companies = [
	{ name: "Vodafone", logo: "/vodafone.svg" },
	{ name: "Intel", logo: "/intel.svg" },
	{ name: "Tesla", logo: "/tesla.svg" },
	{ name: "AMD", logo: "/amd.svg" },
	{ name: "Teletalk", logo: "/teletalk.svg" },
];

export const featJobs = [
	{
		id: "job-1",
		title: "Email Marketing",
		company: "Revolut",
		location: "Madrid, Spain",
		type: "Full Time",
		description:
			"Revolut is looking for Email Marketing to help team manage campaigns and growth.",
		categories: ["Marketing", "Design"],
		logo: "/Company Logo.svg",
	},
	{
		id: "job-2",
		title: "Brand Designer",
		company: "Dropbox",
		location: "San Francisco, US",
		type: "Full Time",
		description:
			"Dropbox is looking for Brand Designer to help the team build strong visual identity.",
		categories: ["Design", "Business"],
		logo: "/Company Logo-1.svg",
	},
	{
		id: "job-3",
		title: "Email Marketing",
		company: "Pitch",
		location: "Berlin, Germany",
		type: "Full Time",
		description:
			"Pitch is looking for Customer Manager to join marketing team.",
		categories: ["Marketing"],
		logo: "/Company Logo-2.svg",
	},
	{
		id: "job-4",
		title: "Visual Designer",
		company: "Blinklist",
		location: "Granada, Spain",
		type: "Full Time",
		description:
			"Blinklist is looking for Visual Designer to help team design better experiences.",
		categories: ["Design"],
		logo: "/Company Logo-3.svg",
	},
	{
		id: "job-5",
		title: "Product Designer",
		company: "ClassPass",
		location: "Manchester, UK",
		type: "Full Time",
		description:
			"ClassPass is looking for Product Designer to help improve product usability.",
		categories: ["Marketing", "Design"],
		logo: "/Company Logo-4.svg",
	},
	{
		id: "job-6",
		title: "Lead Designer",
		company: "Canva",
		location: "Ontario, Canada",
		type: "Full Time",
		description:
			"Canva is looking for Lead Engineer to help develop new features.",
		categories: ["Design", "Business"],
		logo: "/Company Logo-5.svg",
	},
	{
		id: "job-7",
		title: "Brand Strategist",
		company: "GoDaddy",
		location: "Marseille, France",
		type: "Full Time",
		description: "GoDaddy is looking for Brand Strategist to join the team.",
		categories: ["Marketing"],
		logo: "/Company Logo-6.svg",
	},
	{
		id: "job-8",
		title: "Data Analyst",
		company: "Twitter",
		location: "San Diego, US",
		type: "Full Time",
		description:
			"Twitter is looking for Data Analyst to help team analyze performance data.",
		categories: ["Technology"],
		logo: "/Company Logo-7.svg",
	},
];
export const latestOpenJobs = [
	{
		id: "job-1",
		title: "Social Media Assistant",
		company: "Nomad",
		location: "Paris, France",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/nomad.svg",
	},
	{
		id: "job-2",
		title: "Social Media Assistant",
		company: "Netlify",
		location: "Paris, France",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/netlify.svg",
	},
	{
		id: "job-3",
		title: "Brand Designer",
		company: "Dropbox",
		location: "San Francisco, USA",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/dropbox.svg",
	},
	{
		id: "job-4",
		title: "Brand Designer",
		company: "Maze",
		location: "San Francisco, USA",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/maze.svg",
	},
	{
		id: "job-5",
		title: "Interactive Developer",
		company: "Terraform",
		location: "Hamburg, Germany",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/terraform.svg",
	},
	{
		id: "job-6",
		title: "Interactive Developer",
		company: "Udacity",
		location: "Hamburg, Germany",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/udacity.svg",
	},
	{
		id: "job-7",
		title: "HR Manager",
		company: "Packer",
		location: "Lucern, Switzerland",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/packer.svg",
	},
	{
		id: "job-8",
		title: "HR Manager",
		company: "Webflow",
		location: "Lucern, Switzerland",
		type: "Full-Time",
		categories: ["Marketing", "Design"],
		logo: "/webflow.svg",
	},
];
